name: Build Kivy APK with Community Action

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.2.1
        id: buildozer
        with:
          command: buildozer android debug
          build_id: anqaa-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildozer.outputs.filename_debug }}
          path: ${{ steps.buildozer.outputs.filename_debug }}
